Repository danielindracahyadi/progress-tracker-frontend, pull requests merged in 2019-09, with the labels that each got.

#16 Login scene
  src/app/app.component.html
  src/app/app.module.ts
  src/app/core-ui/button/button.component.sass
  src/app/core-ui/text-view/text-view.component.sass
  src/app/pages/login-scene/background-login.svg
  src/app/pages/login-scene/login-scene.component.html
  src/app/pages/login-scene/login-scene.component.sass
  src/app/pages/login-scene/login-scene.component.ts
  src/index.html
  src/styles.sass
Labels: Approved with Minor Suggestion

#18 Check box2
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/core-ui/check-box/check-box.component.html
  src/app/core-ui/check-box/check-box.component.sass
  src/app/core-ui/check-box/check-box.component.ts
Labels: Approved with Minor Suggestion

#19 [User] Report Detail
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/card-report-task/card-report-task.component.html
  src/app/components/card-report-task/card-report-task.component.sass
  src/app/components/card-report-task/card-report-task.component.ts
  src/app/components/card-report-title/card-report-title.component.html
  src/app/components/card-report-title/card-report-title.component.sass
  src/app/components/card-report-title/card-report-title.component.ts
  src/app/core-ui/check-box/check-box.component.sass
  src/app/pages/report-detail/report-detail.component.html
  src/app/pages/report-detail/report-detail.component.sass
  src/app/pages/report-detail/report-detail.component.ts
  src/app/svg/group1191/group1191.component.html
  src/app/svg/group1191/group1191.component.ts
  src/app/svg/group1192/group1192.component.html
  src/app/svg/group1192/group1192.component.ts
Labels: Approved with Minor Suggestion

#22 Update add report
  src/app/app.component.html
  src/app/components/card-add-report-detail/card-add-report-detail.component.html
  src/app/components/card-add-report-detail/card-add-report-detail.component.ts
  src/app/components/card-add-report-dropdown/card-add-report-dropdown.component.html
  src/app/components/card-add-report-dropdown/card-add-report-dropdown.component.ts
  src/app/core-ui/dropdown/dropdown.component.html
  src/app/core-ui/dropdown/dropdown.component.ts
  src/app/pages/add-report/add-report.component.ts
Labels: APPROVED

#15 [Component] Home Card Component
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/card/card.component.html
  src/app/components/card/card.component.sass
  src/app/components/card/card.component.ts
  src/app/core-ui/button/button.component.ts
  src/app/pages/home-report/home-report.component.html
  src/app/pages/home-report/home-report.component.sass
  src/app/pages/home-report/home-report.component.ts
  src/index.html
Labels: APPROVED

#23 [CoreUI] [Admin] expansionTile
  src/app/app.module.ts
  src/app/core-ui/expansion-tile/expansion-tile.component.html
  src/app/core-ui/expansion-tile/expansion-tile.component.sass
  src/app/core-ui/expansion-tile/expansion-tile.component.ts
Labels: APPROVED

#24 [Scene] [User] Update add report ver2
  src/app/app.component.html
  src/app/app.module.ts
  src/app/app.service.ts
  src/app/components/card-add-report-detail/card-add-report-detail.component.ts
  src/app/components/card-add-report-dropdown/card-add-report-dropdown.component.html
  src/app/components/card-add-report-dropdown/card-add-report-dropdown.component.ts
  src/app/components/card-add-report-task/card-add-report-task.component.ts
  src/app/components/card/card.component.ts
  src/app/core-ui/dropdown/dropdown.component.html
  src/app/core-ui/dropdown/dropdown.component.sass
  src/app/core-ui/dropdown/dropdown.component.ts
  src/app/pages/add-report/add-report.component.html
  src/app/pages/add-report/add-report.component.sass
  src/app/pages/add-report/add-report.component.ts
Labels: ready for review

#27 [Page] [User] Report Detail (Revisi Sidenav)
  src/app/app.component.html
  src/app/app.component.ts
  src/app/pages/admin/report-detail/report-detail.component.sass
  src/app/pages/report-detail/report-detail.component.html
  src/app/pages/report-detail/report-detail.component.sass
  src/app/pages/report-detail/report-detail.component.ts
Labels: APPROVED

#25 [Page] [Admin] Main dashboard
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.service.ts
  src/app/components/card/card.component.ts
  src/app/core-ui/dropdown/dropdown.component.html
  src/app/core-ui/dropdown/dropdown.component.sass
  src/app/core-ui/dropdown/dropdown.component.ts
  src/app/core-ui/expansion-tile/expansion-tile.component.html
  src/app/core-ui/expansion-tile/expansion-tile.component.sass
  src/app/pages/admin/main-dashboard/main-dashboard.component.html
  src/app/pages/admin/main-dashboard/main-dashboard.component.sass
  src/app/pages/admin/main-dashboard/main-dashboard.component.ts
Labels: APPROVED

#29 [Page] [Admin] Main Dashboard Time
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/constants/index.ts
  src/app/core-ui/expansion-tile/expansion-tile.component.html
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.html
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.sass
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.component.html
  src/app/pages/admin/main-dashboard/main-dashboard.component.sass
  src/app/types/index.ts
Labels: Approved with Minor Suggestion

#30 [USER] [PAGE] Updatehomereport
  src/app/app.component.html
  src/app/app.service.ts
  src/app/components/card/card.component.html
  src/app/components/card/card.component.sass
  src/app/components/card/card.component.ts
  src/app/core-ui/dropdown/dropdown.component.html
  src/app/pages/home-report/home-report.component.html
  src/app/pages/home-report/home-report.component.ts
  src/app/types/index.ts
Labels: Approved with Minor Suggestion

#32 [Page][Admin] Main Dashboard (Update Dropdown dan InputField)
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.service.ts
  src/app/core-ui/expansion-tile/expansion-tile.component.html
  src/app/core-ui/expansion-tile/expansion-tile.component.sass
  src/app/core-ui/expansion-tile/expansion-tile.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.component.html
  src/app/pages/admin/main-dashboard/main-dashboard.component.sass
  src/app/pages/admin/main-dashboard/main-dashboard.component.ts
  src/app/svg/group1286/group1286.component.html
  src/app/svg/group1286/group1286.component.ts
Labels: Approved with Minor Suggestion

#35 [Documentation] UPDATE V.1
  README.md
Labels: APPROVED

#28 [Pages] login admin test
  src/app/app.component.html
  src/app/app.module.ts
  src/app/core-ui/text-input/text-input.component.html
  src/app/core-ui/text-input/text-input.component.sass
  src/app/core-ui/text-input/text-input.component.ts
  src/app/pages/admin/login-admin/login-admin.component.html
  src/app/pages/admin/login-admin/login-admin.component.sass
  src/app/pages/admin/login-admin/login-admin.component.ts
  src/app/pages/login-scene/login-scene.component.html
  src/assets/Codify_Logo_Black.png
  src/index.html
Labels: APPROVED

#37 [User&Admin] [CoreUI & Component] Update Modal, ButtonAdmin, Button
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/modal/modal-data-admin-add/modal-data-admin-add.component.html
  src/app/components/modal/modal-data-admin-add/modal-data-admin-add.component.ts
  src/app/components/modal/modal-data-admin-delete/modal-data-admin-delete.component.html
  src/app/components/modal/modal-data-admin-delete/modal-data-admin-delete.component.ts
  src/app/components/modal/modal-data-admin-edit/modal-data-admin-edit.component.html
  src/app/components/modal/modal-data-admin-edit/modal-data-admin-edit.component.ts
  src/app/components/modal/modal-data-user-confirmation/modal-data-user-confirmation.component.html
  src/app/components/modal/modal-data-user-confirmation/modal-data-user-confirmation.component.ts
  src/app/components/modal/modal-data-user-delete/modal-data-user-delete.component.html
  src/app/components/modal/modal-data-user-delete/modal-data-user-delete.component.ts
  src/app/components/modal/modal-data-user-submit/modal-data-user-submit.component.html
  src/app/components/modal/modal-data-user-submit/modal-data-user-submit.component.ts
  src/app/components/modal/modal.component.html
  src/app/components/modal/modal.component.ts
  src/app/components/modal/modal.service.ts
  src/app/core-ui/button-admin/button-admin.component.html
  src/app/core-ui/button-admin/button-admin.component.sass
  src/app/core-ui/button-admin/button-admin.component.ts
  src/app/core-ui/button/button.component.sass
  src/app/core-ui/text-input/text-input.component.sass
  src/app/core-ui/text-input/text-input.component.ts
  src/app/core-ui/text-view/text-view.component.sass
  src/app/svg/group1225/group1225.component.html
  src/app/svg/group1225/group1225.component.ts
  src/app/svg/group1226/group1226.component.html
  src/app/svg/group1226/group1226.component.ts
  src/app/svg/group1227/group1227.component.html
  src/app/svg/group1227/group1227.component.ts
  src/assets/Group_1225.svg
  src/assets/Group_1226.svg
  src/assets/Group_1227.svg
Labels: APPROVED

#36 Routing
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.service.ts
  src/app/components/card/card.component.html
  src/app/components/card/card.component.sass
  src/app/components/card/card.component.ts
  src/app/core-ui/dropdown/dropdown.component.html
  src/app/pages/home-report/home-report.component.ts
  src/app/pages/login-scene/login-scene-routing.module.ts
  src/app/pages/login-scene/login-scene.component.html
  src/app/pages/login-scene/login-scene.component.sass
  src/app/pages/login-scene/login-scene.component.ts
  src/app/pages/login-scene/login-scene.module.ts
  src/app/pages/login-scene/login-scene.service.ts
  tslint.json
Labels: Approved with Minor Suggestion
