Repository danielindracahyadi/progress-tracker-frontend, pull requests merged in 2019-10, with the labels that each got.

#38 [Header] Header
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.service.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.sass
  src/app/components/header/header.component.ts
  src/app/core-ui/expansion-tile/expansion-tile.component.html
  src/app/core-ui/text-input/text-input.component.sass
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.html
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.component.html
  src/app/pages/admin/main-dashboard/main-dashboard.component.sass
  src/app/pages/login-scene/login-scene.component.html
  src/app/pages/login-scene/login-scene.component.ts
  src/app/svg/arrow-down/arrow-down.component.html
  src/app/svg/arrow-down/arrow-down.component.ts
  src/app/types/index.ts
Labels: APPROVED

#39 [Admin Scene] Routing admin
  src/app/core-ui/custom-text-view/custom-text-view.component.spec.ts
  src/app/core-ui/custom-text-view/custom-text-view.component.ts
  src/app/pages/admin/login-admin/login-admin.component.html
  src/app/pages/admin/login-admin/login-admin.component.ts
  src/app/pages/login-scene/login-scene.component.html
Labels: APPROVED

#41 [FIX] delete custom-text-view
  package-lock.json
  src/app/core-ui/custom-text-view/custom-text-view.component.spec.ts
  src/app/core-ui/custom-text-view/custom-text-view.component.ts
  tslint.json
Labels: ready for review

#42 [Header] Update logo header
  src/app/components/header/header.component.html
  src/app/pages/report-detail/report-detail.component.html
Labels: ready for review

#43 [Component] Slider
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/card-add-report-task/card-add-report-task.component.html
  src/app/core-ui/check-box/check-box.component.html
  src/app/core-ui/check-box/check-box.component.sass
  src/app/core-ui/check-box/check-box.component.ts
Labels: APPROVED by 9/10 dentist in the world

#44 [Documentation] Update V.2
  README.md
Labels: APPROVED by 9/10 dentist in the world, documentation, ready for review

#45 [Documentation] Update V.3
  README.md
Labels: APPROVED by 9/10 programmer in the world, documentation, ready for review

#46 Conn backend add report
  src/app/app.service.ts
  src/app/components/card-add-report-detail/card-add-report-detail.component.ts
  src/app/components/card-add-report-dropdown/card-add-report-dropdown.component.html
  src/app/components/card-add-report-dropdown/card-add-report-dropdown.component.ts
  src/app/core-ui/dropdown/dropdown.component.html
  src/app/core-ui/dropdown/dropdown.component.ts
  src/app/pages/add-report/add-report.component.html
  src/app/pages/add-report/add-report.component.ts
  src/app/pages/add-report/add-report.service.ts
  src/app/types/index.ts
Labels: Approved with Minor Suggestion, ready for review

#47 [CONNECT BACKEND] [Admin] HOME (Project, Role, User)
  src/app/core-ui/dropdown/dropdown.component.ts
  src/app/core-ui/expansion-tile/expansion-tile.component.html
  src/app/core-ui/expansion-tile/expansion-tile.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.component.html
  src/app/pages/admin/main-dashboard/main-dashboard.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.service.ts
Labels: APPROVED by 9/10 programmer in the world
