Repository danielindracahyadi/progress-tracker-frontend, pull requests merged in 2019-12, with the labels that each got.

#60 [Documentation][FIX] typo
  README.md
Labels: APPROVED by 9/10 programmer in the world, documentation

#59 CardHome Blue and Red Card Done
  src/app/components/card/card.component.html
  src/app/components/card/card.component.sass
  src/app/components/card/card.component.ts
  src/app/pages/home-report/home-report.component.html
  src/app/pages/home-report/home-report.component.ts
  src/app/pages/home-report/home-report.service.ts
  src/app/pages/report-detail/report-detail.component.ts
  src/app/types/index.ts
Labels: APPROVED by 9/10 programmer in the world

#61 Resolve bug add report date
  src/app/components/card-report-title/card-report-title.component.html
  src/app/components/card-report-title/card-report-title.component.ts
  src/app/components/card/card.component.html
  src/app/components/card/card.component.ts
  src/app/pages/add-report/add-report.component.ts
  src/app/pages/add-report/add-report.service.ts
  src/app/pages/home-report/home-report.component.html
  src/app/pages/home-report/home-report.component.ts
Labels: ready for review

#62 [Documentation] Admin Report Detail Endpoint
  README.md
Labels: APPROVED by 9/10 programmer in the world, documentation

#64 [Modal] [Admin] Update Modal Admin
  src/app/components/modal/modal-data-admin-add-project/modal-data-admin-add-project.component.html
  src/app/components/modal/modal-data-admin-add-project/modal-data-admin-add-project.component.ts
  src/app/components/modal/modal-data-admin-add-role/modal-data-admin-add-role.component.html
  src/app/components/modal/modal-data-admin-add-role/modal-data-admin-add-role.component.ts
  src/app/components/modal/modal-data-admin-add/modal-data-admin-add.component.html
  src/app/components/modal/modal-data-admin-add/modal-data-admin-add.component.ts
Labels: APPROVED by 9/10 programmer in the world

#63 [Documentation] Edit user, role, and project
  README.md
Labels: APPROVED by 9/10 programmer in the world, documentation

#66 ChangeTextInputColor
  src/app/components/card-add-report-task/card-add-report-task.component.sass
  src/app/core-ui/dropdown/dropdown.component.sass
  src/app/core-ui/text-input/text-input.component.sass
  src/app/pages/admin/login-admin/login-admin.component.sass
  src/app/pages/login-scene/login-scene.component.sass
Labels: APPROVED by 9/10 programmer in the world

#67 [CONNECT BACKEND ADMIN] DELETE PROJECT ROLE USER
  src/app/app.component.html
  src/app/app.service.ts
  src/app/components/card-report-title/card-report-title.component.html
  src/app/components/card/card.component.ts
  src/app/components/modal/modal-data-admin-delete/modal-data-admin-delete.component.html
  src/app/components/modal/modal-data-admin-delete/modal-data-admin-delete.component.ts
  src/app/components/modal/modal.component.ts
  src/app/core-ui/expansion-tile/expansion-tile.component.html
  src/app/core-ui/expansion-tile/expansion-tile.component.ts
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.html
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.sass
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.service.ts
Labels: Approved with Minor Suggestion

#65 [BUG] resolve if already login or not
  src/app/pages/add-report/add-report.component.ts
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.component.ts
  src/app/pages/admin/report-detail/report-detail.component.ts
  src/app/pages/home-report/home-report.component.ts
  src/app/pages/report-detail/report-detail.component.ts
Labels: APPROVED by 9/10 programmer in the world

#68 ChangeuserName
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/pages/add-report/add-report.component.html
  src/app/pages/add-report/add-report.component.ts
  src/app/pages/admin/login-admin/login-admin.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.component.html
  src/app/pages/admin/main-dashboard/main-dashboard.component.ts
  src/app/pages/home-report/home-report.component.html
  src/app/pages/home-report/home-report.component.ts
  src/app/pages/login-scene/login-scene.component.ts
  src/app/pages/report-detail/report-detail.component.html
  src/app/pages/report-detail/report-detail.component.ts
Labels: Approved with Minor Suggestion

#70 [Admin] [Report Detail] Report Detail
  src/app/app.module.ts
  src/app/components/modal/modal-data-admin-add-project/modal-data-admin-add-project.component.ts
  src/app/components/modal/modal-data-admin-add-role/modal-data-admin-add-role.component.ts
  src/app/components/modal/modal-data-admin-delete/modal-data-admin-delete.component.ts
  src/app/core-ui/expansion-tile/expansion-tile.component.ts
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.html
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.service.ts
  src/app/pages/admin/report-detail/report-detail.component.html
  src/app/pages/admin/report-detail/report-detail.component.sass
  src/app/pages/admin/report-detail/report-detail.component.ts
Labels: APPROVED by 9/10 programmer in the world

#71 resolve-bug
  src/app/components/modal/modal-data-admin-add-project/modal-data-admin-add-project.component.ts
  src/app/components/modal/modal-data-admin-add-role/modal-data-admin-add-role.component.ts
  src/app/core-ui/expansion-tile/expansion-tile.component.ts
  src/app/pages/add-report/add-report.component.ts
  src/app/pages/admin/login-admin/login-admin.component.html
  src/app/pages/admin/login-admin/login-admin.component.sass
  src/app/pages/admin/login-admin/login-admin.component.ts
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.html
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.component.html
  src/app/pages/admin/main-dashboard/main-dashboard.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.service.ts
  src/app/pages/admin/report-detail/report-detail.component.ts
  src/app/pages/home-report/home-report.component.ts
Labels: APPROVED by 9/10 programmer in the world

#72 [Admin] Main Dashboard Timeline
  src/app/components/modal/modal-data-admin-add-project/modal-data-admin-add-project.component.ts
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.html
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.sass
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.ts
Labels: APPROVED by 9/10 programmer in the world

#73 Revisi Bug (Lihat Detail)
  src/app/app.component.ts
  src/app/app.service.ts
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.component.html
  src/app/pages/admin/main-dashboard/main-dashboard.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.service.ts
  src/app/pages/home-report/home-report.component.html
  src/app/pages/report-detail/report-detail.component.html
  src/app/pages/report-detail/report-detail.component.sass
  src/app/pages/report-detail/report-detail.component.ts
Labels: APPROVED by 9/10 programmer in the world

#74 beresinLoginAdmin
  src/app/core-ui/button/button.component.sass
  src/app/pages/admin/login-admin/login-admin.component.html
  src/app/pages/admin/login-admin/login-admin.component.sass
  src/app/pages/admin/login-admin/login-admin.component.ts
Labels: ready for review

#75 [USER SCENE] [FEATURE] search features
  src/app/pages/home-report/home-report.component.html
  src/app/pages/home-report/home-report.component.sass
  src/app/pages/home-report/home-report.component.ts
Labels: APPROVED by 9/10 programmer in the world
