Repository danielindracahyadi/progress-tracker-frontend, pull requests merged in 2019-11, with the labels that each got.

#49 [Connect Backend] [Admin] Timeline
  src/app/app-routing.module.ts
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.html
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.sass
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.ts
  src/app/types/index.ts
Labels: APPROVED by 9/10 programmer in the world

#51 [Documentation] User Report Detail
  README.md
Labels: APPROVED by 9/10 programmer in the world

#50 [CONNECT BACKEND] [Admin] HOME (Project, Role, User) !!UPDATE!!
  src/app/app.component.html
  src/app/core-ui/expansion-tile/expansion-tile.component.html
  src/app/core-ui/expansion-tile/expansion-tile.component.sass
  src/app/core-ui/expansion-tile/expansion-tile.component.ts
  src/app/pages/admin/main-dashboard/main-dashboard.component.html
  src/app/pages/admin/main-dashboard/main-dashboard.component.ts
  src/app/types/index.ts
Labels: APPROVED by 9/10 programmer in the world

#53 [Connect Backend] [Admin] Timeline Update
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.html
  src/app/pages/admin/main-dashboard-time/main-dashboard-time.component.sass
  src/app/types/index.ts
Labels: ready for review

#52 Connect admin login
  src/app/app.module.ts
  src/app/pages/admin/login-admin/login-admin-routing.module.ts
  src/app/pages/admin/login-admin/login-admin.component.html
  src/app/pages/admin/login-admin/login-admin.component.sass
  src/app/pages/admin/login-admin/login-admin.component.ts
  src/app/pages/admin/login-admin/login-admin.module.ts
  src/app/pages/admin/login-admin/login-admin.service.ts
Labels: APPROVED by 9/10 programmer in the world

#54 [Connect] [User] Report Detail
  src/app/app.component.ts
  src/app/app.service.ts
  src/app/components/card/card.component.ts
  src/app/pages/home-report/home-report.service.ts
  src/app/pages/report-detail/report-detail.component.html
  src/app/pages/report-detail/report-detail.component.sass
  src/app/pages/report-detail/report-detail.component.ts
Labels: ready for review

#56 Edit login admin
  src/app/app.component.html
  src/app/pages/admin/login-admin/login-admin.component.html
  src/app/pages/admin/login-admin/login-admin.component.sass
Labels: APPROVED by 9/10 programmer in the world

#55 [SCENE] Conn backend add report
  src/app/app.module.ts
  src/app/app.service.ts
  src/app/components/card-add-report-detail/card-add-report-detail.component.html
  src/app/components/card-add-report-detail/card-add-report-detail.component.ts
  src/app/components/card-add-report-dropdown/card-add-report-dropdown.component.html
  src/app/components/card-add-report-dropdown/card-add-report-dropdown.component.sass
  src/app/components/card-add-report-dropdown/card-add-report-dropdown.component.ts
  src/app/components/card-add-report-task/card-add-report-task.component.html
  src/app/components/card-add-report-task/card-add-report-task.component.sass
  src/app/components/card-add-report-task/card-add-report-task.component.ts
  src/app/core-ui/check-box/check-box.component.html
  src/app/core-ui/check-box/check-box.component.ts
  src/app/core-ui/dropdown/dropdown.component.ts
  src/app/pages/add-report/add-report.component.html
  src/app/pages/add-report/add-report.component.ts
  src/app/pages/add-report/add-report.service.ts
Labels: APPROVED by 9/10 programmer in the world

#58 [Documentation] Delete User, Role, and Project
  README.md
Labels: APPROVED by 9/10 programmer in the world, documentation
