Repository danielindracahyadi/progress-tracker-frontend, pull requests merged in 2019-08, with the labels that each got.

#1 test fian commit
  src/app/app.component.html
Labels: Approved

#4 [Scene] Login
  src/app/app.component.html
Labels: Approved

#3 [Scene] Login
  src/app/app.component.html
Labels: Approved

#2 [Scene] Login
  src/app/app.component.html
Labels: Approved

#6 app-custom-text-view update
  src/app/app.component.html
  src/app/app.module.ts
  src/app/core-ui/custom-text-view/custom-text-view.component.spec.ts
  src/app/core-ui/custom-text-view/custom-text-view.component.ts
Labels: APPROVED

#10 [Core UI] text input
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/core-ui/text-input/text-input.component.ts
Labels: APPROVED

#7 Core UI Button
  angular.json
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/core-ui/custom-button/custom-button.component.spec.ts
  src/app/core-ui/custom-button/custom-button.component.ts
  tslint.json
Labels: Approved with Minor Suggestion

#11 Datepicker core ui
  angular.json
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.sass
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/core-ui/button/button.component.ts
  src/app/core-ui/custom-button/custom-button.component.spec.ts
  src/app/core-ui/custom-text-view/custom-text-view.component.spec.ts
  src/app/core-ui/datepicker/datepicker.component.ts
  src/app/core-ui/text-view/text-view.component.ts
  src/main.ts
  tsconfig.json
Labels: Approved with Minor Suggestion

#12 update compostion core ui version 1
  src/app/app.component.html
  src/app/core-ui/button/button.component.html
  src/app/core-ui/button/button.component.sass
  src/app/core-ui/button/button.component.ts
  src/app/core-ui/datepicker/datepicker.component.html
  src/app/core-ui/datepicker/datepicker.component.sass
  src/app/core-ui/datepicker/datepicker.component.ts
  src/app/core-ui/text-input/text-input.component.html
  src/app/core-ui/text-input/text-input.component.sass
  src/app/core-ui/text-input/text-input.component.ts
  src/app/core-ui/text-view/text-view.component.html
  src/app/core-ui/text-view/text-view.component.sass
  src/app/core-ui/text-view/text-view.component.ts
Labels: APPROVED

#13 'updateFinalDropdown'
  src/app/app.component.html
  src/app/app.module.ts
  src/app/core-ui/dropdown/dropdown.component.html
  src/app/core-ui/dropdown/dropdown.component.sass
  src/app/core-ui/dropdown/dropdown.component.ts
Labels: APPROVED
